name: Cairo CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protostar
      run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
    - name: Restart terminal
      run: reset
    - name: Protostar build
      run: protostar build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protostar
      run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
    - name: Restart terminal
      run: reset
    - name: Protostar tests
      run: protostar test
