# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Cairo CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protostar
      run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
    - name: Protostar build
      run: protostar build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protostar
      run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
    - name: Protostar tests
      run: protostar test
