name: Cairo CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Protostar build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Protostar
        uses: sambarnes/protostar-toolchain@main
      - name: Build project
        run: protostar build

  test:
    name: Protostar tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Protostar
        uses: sambarnes/protostar-toolchain@main
      - name: Run tests
        run: protostar test
